package luk

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	FileUploadApi
	LukScheduledTaskApi
	LukScheduledTaskLogApi
	LukNftApi
	LukNftBuyApi
	LukRevenueApi
	LukRevenueDetailedApi
	LukConstantApi
	LukUserApi
	LukWalletLogApi
	LukNftTransferApi
	LukBannerApi
	LukInformationApi
	LukInformationTypeApi
	LukWithdrawApplyApi
	LukWithdrawHistoryApi
	LukComboApi
	LukComboBuyApi
	LukConfigApi
	LukUserAddressApi
	LukDappApi
	LukPartnerApi
	LukRevenueNftApi
	LukRevenueDetailedNftApi
	LukPanelDataApi
	LukHeritageMetaverseApi
	LukRevenueHeritageApi
	LukRevenueDetailedHeritageApi
	LukHeritageMetaverseOldApi
	LukHeritageLpApi
	LukRebateApi
	LukWithdrawBlacklistApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
