package luk

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	UploaderRouter
	LukScheduledTaskRouter
	LukScheduledTaskLogRouter
	LukNftRouter
	LukNftBuyRouter
	LukRevenueRouter
	LukRevenueDetailedRouter
	LukConstantRouter
	LukUserRouter
	LukWalletLogRouter
	LukNftTransferRouter
	LukBannerRouter
	LukInformationRouter
	LukInformationTypeRouter
	LukWithdrawApplyRouter
	LukWithdrawHistoryRouter
	LukComboRouter
	LukComboBuyRouter
	LukConfigRouter
	LukUserAddressRouter
	LukDappRouter
	LukPartnerRouter
	LukRevenueNftRouter
	LukRevenueDetailedNftRouter
	LukPanelDataRouter
	LukHeritageMetaverseRouter
	LukRevenueHeritageRouter
	LukRevenueDetailedHeritageRouter
	LukHeritageMetaverseOldRouter
	LukHeritageLpRouter
	LukRebateRouter
	LukWithdrawBlacklistRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
