version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是175.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '175.7.0.0/16'

# 设置mysql，redis持久化保存
volumes:
  mysql:
  redis:


services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
      args:
        configFile: config.docker.yaml
    container_name: luk-web
    restart: always
    ports:
      - '10201:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 175.7.0.11
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: luk-server
    restart: always
    ports:
      - '10202:8888'
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./server/uploads:/go/src/github.com/flipped-aurora/gin-vue-admin/server/uploads
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      network:
        ipv4_address: 175.7.0.12
  mysql:
    image: mysql:8.0.21 # 如果您是 arm64 架构：如 MacOS 的 M1，请修改镜像为 image: mysql/mysql-server:8.0.21
    container_name: luk-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - "10203:3306" # host物理直接映射端口为10203
    environment:
      MYSQL_DATABASE: 'qmPlus' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'lukQWERTY' # root管理员用户密码
      
      # MYSQL_DATABASE: 'luk_gva' # 初始化启动时要创建的数据库的名称
      # MYSQL_ROOT_PASSWORD: '' # root管理员用户密码





    volumes:
      - mysql:/var/lib/mysql
    networks:
      network:
        ipv4_address: 175.7.0.13

  redis:
    image: redis:6.0.6
    container_name: luk-redis # 容器名
    restart: always
    ports:
      - '10204:6379'
    volumes:
      - redis:/data
    networks:
      network:
        ipv4_address: 175.7.0.14
