package luk

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	FileUploadService
	LukScheduledTaskService
	LukScheduledTaskLogService
	LukNftService
	LukNftBuyService
	LukRevenueService
	LukRevenueDetailedService
	LukConstantService
	LukUserService
	LukWalletLogService
	LukNftTransferService
	LukTokenBlockHigthService
	LukBlockScanRecordService
	LukBannerService
	LukInformationService
	LukInformationTypeService
	LukWithdrawApplyService
	LukWithdrawHistoryService
	LukComboService
	LukComboBuyService
	LukUserAddressService
	LukPoolBasicService
	LukDestroyService
	LukReflowService
	LukDappService
	LukPartnerService
	LukExchangeRecordsService
	LukRevenueNftService
	LukRevenueDetailedNftService
	LukPanelDataService
	LukHeritageMetaverseService
	LukRevenueHeritageService
	LukRevenueDetailedHeritageService
	LukHeritageMetaverseOldService
	LukHeritageLpService
	LukRebateService
	LukWithdrawBlacklistService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
